### ISSUE TITLE
Option to use the cedar jdk for lower slug size

### ISSUE THREAD

**Issue by robinheghan** [heroku/lein-heroku#3]
Using the JVM that is provided by the cedar stack should reduce slug size by aprox 50Mb. For apps that don't require Java 8, this should improve start-up time.

**Comment by danielcompton** [comment]
You may find that using Java 8 will give you more speed benefits than including the default Cedar JDK.

**Comment by robinheghan** [comment]
For an app that has io as its bottleneck, in addition to not being close to max out cpu, startup time is more important than raw speed.

**Comment by danielcompton** [comment]
Ok, I'd be keen to see some benchmarks on startup time when you're finished to see what kind of an improvement is available. We're also finding startup time is slow.

**Comment by jkutner** [comment]
I'm working in support for this by allowing custom buildpacks. Right now, the plugin defaults to using the [jvm-common buildpack](https://github.com/heroku/heroku-buildpack-jvm-common), which installs the JDK. But you will be able to configure something like the [null buildpack](https://github.com/ryandotsmith/null-buildpack) to use the stack JDK. For example:

``` clojure
:heroku {:buildpacks ["https://github.com/ryandotsmith/null-buildpack"]}
```

This is a bit of a workaround. In the future I'll see if I can add direct support for this case.

**Comment by jkutner** [comment]
@Skinney released 0.5.3 with the above feature. please let me know if this works for you

**Comment by robinheghan** [comment]
Cool, I'll test it out immedietly. Will the null buildpack work with a JVM7 uberjar?

**Comment by jkutner** [comment]
@Skinney yes it will work with JDK7. All that does is replace the buildpack that would normally install the 50mb JVM.

**Comment by robinheghan** [comment]
My app works exactly as it used to, but this time with a slug size of 8Mb. I had thought I would get a noticable improvement in startup time (I once published a Go app to heroku, and that seemed to startup in no time on a free dyno) but I didn't notice any particular improvements.

Anyway. I think the solution you have with regards to custom buildpacks is good enough. Thank you for this :)
